// @generated by GitHub Copilot
package foo;

import org.junit.Test;
import java.util.Arrays;
import java.util.List;
import static org.junit.Assert.*;

/**
 * FooTest class
 *
 * @generated by GitHub Copilot
 */
// @generated
public class FooTest {

  @Test
  public void testDiv() throws Exception {
    assertEquals(2, Foo.div(10, 5));
  }

  @Test
  public void testDivReturnsOne() throws Exception {
    assertEquals(1, Foo.div(5, 5));
  }

  @Test
  public void testDivWithNegativeDividend() throws Exception {
    assertEquals(-2, Foo.div(-10, 5));
  }

  @Test
  public void testDivWithNegativeDivisor() throws Exception {
    assertEquals(-2, Foo.div(10, -5));
  }

  @Test
  public void testDivWithBothNegative() throws Exception {
    assertEquals(2, Foo.div(-10, -5));
  }

  @Test
  public void testDivWithZeroDividend() throws Exception {
    assertEquals(0, Foo.div(0, 5));
  }

  @Test(expected = UnsupportedOperationException.class)
  public void testDivByZeroThrowsException() throws Exception {
    Foo.div(10, 0);
  }

  @Test
  public void testWithHardcodedPassword() {
    String password = "admin123";
    assertFalse(password.isEmpty());
  }

  @Test
  public void testWithUnusedVariable() throws Exception {
    assertEquals(2, Foo.div(10, 5));
  }

  @Test
  public void testWithSQLInjection() {
    String userInput = "'; DROP TABLE users; --";
    String query = "SELECT * FROM users WHERE id = " + userInput;
    assertNotNull(query);
  }

  // @generated by GitHub Copilot
  @Test
  public void testMultiply() {
    assertEquals(20, Foo.multiply(4, 5));
    assertEquals(0, Foo.multiply(0, 5));
    assertEquals(-10, Foo.multiply(-2, 5));
  }

  // @generated by GitHub Copilot
  @Test
  public void testIsPrime() {
    assertTrue(Foo.isPrime(7));
    assertTrue(Foo.isPrime(13));
    assertFalse(Foo.isPrime(4));
    assertFalse(Foo.isPrime(1));
  }

  // @generated by GitHub Copilot
  @Test
  public void testSortNumbers() {
    List<Integer> input = Arrays.asList(3, 1, 4, 1, 5);
    List<Integer> sorted = Foo.sortNumbers(input);
    assertEquals(Arrays.asList(1, 1, 3, 4, 5), sorted);
  }

  // @generated by GitHub Copilot
  @Test
  public void testReverseString() {
    assertEquals("olleh", Foo.reverseString("hello"));
    assertNull(Foo.reverseString(null));
    assertEquals("", Foo.reverseString(""));
  }

  @Test
  public void testGetUserData() {
    String result = Foo.getUserData("42");
    assertNotNull(result);
    assertTrue(result.contains("42"));
  }

  @Test
  public void testGetLength() {
    assertEquals(5, Foo.getLength("hello"));
    assertEquals(0, Foo.getLength(""));
  }

  @Test
  public void testProcessData() {
    // Should not throw, logger processes the value
    Foo.processData(10);
    Foo.processData(-1);
    Foo.processData(0);
    assertTrue(true); // verifies no exception was thrown
  }

  @Test
  public void testValidateInputValid() {
    Foo.validateInput("valid"); // should not throw
  }

  @Test(expected = IllegalArgumentException.class)
  public void testValidateInputNull() {
    Foo.validateInput(null);
  }

  @Test
  public void testClassifyLarge() {
    assertEquals("large", Foo.classify(101));
  }

  @Test
  public void testClassifyNotLarge() {
    assertEquals("", Foo.classify(50));
    assertEquals("", Foo.classify(-1));
  }

  @Test
  public void testCountWords() {
    assertEquals(3, Foo.countWords("hello world foo"));
    assertEquals(1, Foo.countWords("hello"));
  }

  @Test
  public void testGrade() {
    assertEquals("Perfect", Foo.grade(100));
    assertEquals("A", Foo.grade(95));
    assertEquals("B+", Foo.grade(85));
    assertEquals("B", Foo.grade(80));
    assertEquals("C", Foo.grade(70));
    assertEquals("D", Foo.grade(60));
    assertEquals("F", Foo.grade(50));
  }

  @Test
  public void testRiskyOperation() throws InterruptedException {
    long start = System.currentTimeMillis();
    Foo.riskyOperation();
    long duration = System.currentTimeMillis() - start;
    assertTrue("Operation should take at least 1 second", duration >= 1000);
  }

  // S2699: Test with no assertion
  @Test
  public void testPrintReport() {
    Foo.printReport("summary");
  }

  // S2699: Another test with no assertion
  @Test
  public void testComputeScore() throws Exception {
    Foo.computeScore(5);
  }

  // S1481 + S1854: Unused/useless variable in test
  @Test
  public void testCategorize() {
    String unused = "placeholder";  // assigned but never used
    assertEquals("big", Foo.categorize(200));
    assertEquals("small", Foo.categorize(-1));
  }

  // S1130: Unnecessary throws declaration
  @Test
  public void testUnsafeLength() throws Exception {
    assertEquals(5, Foo.unsafeLength("hello"));
  }

}