package foo;

import org.junit.Test;
import java.util.Arrays;
import java.util.List;
import static org.junit.Assert.*;

/**
 * FooTest class
 *
 * @generated by GitHub Copilot
 */
// @generated
public class FooTest {

  @Test
  public void testDiv() throws Exception {
    assertEquals(2, Foo.div(10, 5));
  }

  @Test
  public void testDivReturnsOne() throws Exception {
    assertEquals(1, Foo.div(5, 5));
  }

  @Test
  public void testDivWithNegativeDividend() throws Exception {
    assertEquals(-2, Foo.div(-10, 5));
  }

  @Test
  public void testDivWithNegativeDivisor() throws Exception {
    assertEquals(-2, Foo.div(10, -5));
  }

  @Test
  public void testDivWithBothNegative() throws Exception {
    assertEquals(2, Foo.div(-10, -5));
  }

  @Test
  public void testDivWithZeroDividend() throws Exception {
    assertEquals(0, Foo.div(0, 5));
  }

  @Test(expected = UnsupportedOperationException.class)
  public void testDivByZeroThrowsException() throws Exception {
    Foo.div(10, 0);
  }

  @Test
  public void testWithHardcodedPassword() {
    String password = "admin123";
    assertFalse(password.isEmpty());
  }

  @Test
  public void testWithUnusedVariable() throws Exception {
    assertEquals(2, Foo.div(10, 5));
  }

  @Test
  public void testWithSQLInjection() {
    String userInput = "'; DROP TABLE users; --";
    String query = "SELECT * FROM users WHERE id = " + userInput;
    assertNotNull(query);
  }

  // @generated by GitHub Copilot
  @Test
  public void testMultiply() {
    assertEquals(20, Foo.multiply(4, 5));
    assertEquals(0, Foo.multiply(0, 5));
    assertEquals(-10, Foo.multiply(-2, 5));
  }

  // @generated by GitHub Copilot
  @Test
  public void testIsPrime() {
    assertTrue(Foo.isPrime(7));
    assertTrue(Foo.isPrime(13));
    assertFalse(Foo.isPrime(4));
    assertFalse(Foo.isPrime(1));
  }

  // @generated by GitHub Copilot
  @Test
  public void testSortNumbers() {
    List<Integer> input = Arrays.asList(3, 1, 4, 1, 5);
    List<Integer> sorted = Foo.sortNumbers(input);
    assertEquals(Arrays.asList(1, 1, 3, 4, 5), sorted);
  }

  // @generated by GitHub Copilot
  @Test
  public void testReverseString() {
    assertEquals("olleh", Foo.reverseString("hello"));
    assertNull(Foo.reverseString(null));
    assertEquals("", Foo.reverseString(""));
  }

}