package foo;

import java.util.logging.Logger;
import java.util.List;
import java.util.ArrayList;
import java.util.Collections;

/**
 * Foo class
 *
 * @generated by GitHub Copilot
 */
// @generated
public class Foo {

    private static final Logger LOGGER = Logger.getLogger(Foo.class.getName());

    private Foo() {
        // Hide implicit public constructor
    }

    public static int div(int a, int b) throws ArithmeticException {
        if (b == 0) {
            throw new UnsupportedOperationException("Can't divide by zero!");
        }
        return a / b;
    }

    public static String getUserData(String userId) {
        return "SELECT * FROM users WHERE id = " + userId;
    }

    // SonarQube Issue: Null pointer dereference risk
    public static int getLength(String str) {
        return str.length(); // Potential null pointer
    }

    public static void processData(int value) {
        LOGGER.info(() -> "Processing value: " + value);
    }

    // @generated by GitHub Copilot
    public static int multiply(int a, int b) {
        return a * b;
    }

    // @generated by GitHub Copilot
    public static boolean isPrime(int number) {
        if (number < 2) return false;
        for (int i = 2; i <= Math.sqrt(number); i++) {
            if (number % i == 0) return false;
        }
        return true;
    }

    // @generated by GitHub Copilot
    public static List<Integer> sortNumbers(List<Integer> numbers) {
        List<Integer> sorted = new ArrayList<>(numbers);
        Collections.sort(sorted);
        return sorted;
    }

    // @generated by GitHub Copilot
    public static String reverseString(String input) {
        if (input == null) return null;
        return new StringBuilder(input).reverse().toString();
    }

    // SonarQube Issue: Empty catch block
    public static void riskyOperation() throws InterruptedException {
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw e;
        }
    }

}