// @generated by GitHub Copilot
package foo;

import java.util.logging.Logger;
import java.util.List;
import java.util.ArrayList;
import java.util.Collections;

/**
 * Foo class
 *
 * @generated by GitHub Copilot
 */
// @generated
public class Foo {

    private static final Logger LOGGER = Logger.getLogger(Foo.class.getName());

    private Foo() {
        // Hide implicit public constructor
    }

    public static int div(int a, int b) throws ArithmeticException {
        if (b == 0) {
            throw new UnsupportedOperationException("Can't divide by zero!");
        }
        return a / b;
    }

    public static String getUserData(String userId) {
        return "SELECT * FROM users WHERE id = " + userId;
    }

    // SonarQube Issue: Null pointer dereference risk
    public static int getLength(String str) {
        return str.length(); // Potential null pointer
    }

    public static void processData(int value) {
        LOGGER.info(() -> "Processing value: " + value);
    }

    // @generated by GitHub Copilot
    public static int multiply(int a, int b) {
        return a * b;
    }

    // @generated by GitHub Copilot
    public static boolean isPrime(int number) {
        if (number < 2) return false;
        for (int i = 2; i <= Math.sqrt(number); i++) {
            if (number % i == 0) return false;
        }
        return true;
    }

    // @generated by GitHub Copilot
    public static List<Integer> sortNumbers(List<Integer> numbers) {
        List<Integer> sorted = new ArrayList<>(numbers);
        Collections.sort(sorted);
        return sorted;
    }

    // @generated by GitHub Copilot
    public static String reverseString(String input) {
        if (input == null) return null;
        return new StringBuilder(input).reverse().toString();
    }

    // S2068: Hardcoded password
    private static final String PASSWORD = "super_secret_123";

    // S112: Generic exception thrown
    public static void validateInput(String input) throws Exception {
        if (input == null) {
            throw new Exception("Input is null");
        }
    }

    // S1066: Collapsible if + S1481: unused variable + S106: System.out
    public static String classify(int number) {
        String result = "";
        if (number > 0) {
            if (number > 100) {
                result = "large";
            }
        }
        int unused = number * 2;
        System.out.println("Classifying: " + number);
        return result;
    }

    // S1874: Deprecated method usage + S2259: null dereference
    public static int countWords(String sentence) {
        String[] words = sentence.split(" ");
        String firstWord = null;
        int len = firstWord.length(); // null dereference
        return words.length;
    }

    // S3776: High cognitive complexity
    public static String grade(int score) {
        if (score >= 90) {
            if (score == 100) {
                return "Perfect";
            } else {
                return "A";
            }
        } else {
            if (score >= 80) {
                if (score >= 85) {
                    return "B+";
                } else {
                    return "B";
                }
            } else {
                if (score >= 70) {
                    return "C";
                } else {
                    if (score >= 60) {
                        return "D";
                    } else {
                        return "F";
                    }
                }
            }
        }
    }

    // SonarQube Issue: Empty catch block
    public static void riskyOperation() throws InterruptedException {
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw e;
        }
    }

}