name: Build and SonarQube Analysis

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: [self-hosted, windows]   # your Windows runner labels

    steps:
      - name: Ensure Git is available 
        shell: powershell 
        run: git --version
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and SonarQube Analysis
        shell: powershell
        env:
          SONAR_HOST_URL: 'http://172.16.5.237:9000'
          SONAR_TOKEN: 'squ_cbf71b57b38b7ce7210adf77800277a54cd3e186'
        run: |
          & "C:\Users\Administrator\Downloads\apache-maven-3.9.12-bin\apache-maven-3.9.12\bin\mvn.cmd" `
            clean verify sonar:sonar `
            "-Dsonar.projectKey=java-maven-travis-project" `
            "-Dsonar.host.url=$env:SONAR_HOST_URL" `
            "-Dsonar.token=$env:SONAR_TOKEN"

